version: '3.9'

services:    
  nginx:
    image: nginx:0.0
    volumes:
      - nginxVolume:/etc/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - myNetwork

  spring:
    image: dockerfile:0.0
    volumes:
      - ubuntuVolume:/upload
    tty: true
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - myNetwork

volumes:
  ubuntuVolume:
    external: true
  nginxVolume:
    external: true

networks:
  myNetwork:
    external: true  
