version: '3.9'

services:
  mysql:
    image: mysql:8.3
    volumes:
      - mysqlVolume:/var/lib/mysql
    restart : unless-stopped
    ports:
      - "3306:3306"
    networks:
      - myNetwork

  nginx:
    image: nginx:0.0
    volumes:
      - nginxVolume:/etc/nginx
    restart: unless-stopped
    depends_on:
      - ubuntu
    ports:
      - "80:80"
    networks:
      - myNetwork

  ubuntu:
    image: dockerfile:0.0
    volumes:
      - ubuntuVolume:/upload
    restart: unless-stopped
    environment:
      - LANG=C.UTF-8
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - myNetwork

volumes:
  ubuntuVolume:
    external: true
  nginxVolume:
