naver:
  client_id: t1jPMSOyVjXjL2oqFw4l
  client_secret: m171qS4vOk
  redirect_uri : https://minbong.shop/login/naver/callback

kakao:
  client_id: 0c3786e0d5029e212b8975762dc5b45f
  client_secret: 0sp7hcJBqVsH28t7iKTzrfC6x0y6Q0fc
  redirect_uri : https://minbong.shop/login/kakao/callback

google:
  client_id: 688848632769-rhf1l0ib6bapf8pi0keo9gj1ho6pebhd.apps.googleusercontent.com
  client_secret: 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
  redirect_uri : https://minbong.shop/login/google/callback

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      enabled: true
      location: /upload/
  #datasource:
   #url: jdbc:h2:tcp://localhost/~/MyProject
   #username: sa
   #password:
   #driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://172.18.0.2/shop
    #url: jdbc:mysql://localhost/shop
    username: root
    password: Rhalsqhd#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.apache.coyote.http11: debug

server:
  ssl:
    enabled: false
  servlet:
    session:
      timeout: 3600
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
    include-exception: true
  port: 8081
#    org.hibernate.type: trace


