spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myproject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #datasource:
    #url: jdbc:mysql://localhost:3306/shop
    #username: root
    #password: 1234
    #driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    #database: mysql
    #database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug
    org.apache.coyote.http11: debug
server:
  servlet:
    session:
      timeout: 10

  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
    include-exception: true
#    org.hibernate.type: trace
