spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myproject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    session:
      timeout: 10

  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: on_param
    include-exception: true
#    org.hibernate.type: trace
